### PR TITLE
readme code generations section

### PR DESCRIPTION
**Pull request by vasilich6107**

### CODE REVIEW

**Comment by vasilich6107** [comment]
@joanpablo any news?

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Regarding this PR.

1-) I prefer to have just Documentation changes in one PR
    1.1-) Because the package [reactive_forms_widgets)]([reactive_forms_widgets](https://pub.dev/packages/reactive_forms_widgets)) is already deprecated, I will suggest removing it from the documentation and just leaving the Widgets.

2-)  Remove the code-generation example from the **example** project. Don't make me wrong I think it is a great package and a great idea, but My suggestion is to create the sample folder in that package (reactive_forms_generator) and not here. You keep the reference and link the documentation to that package as you already did in this Documentation, that's great, but the example should belong to that original package and not to the Reactive Forms package.

**Comment by vasilich6107** [comment]
@joanpablo ok, will make the adjustments.

**Comment by joanpablo** [comment]
Hi @vasilich6107,

After several months, I have finally merged the PR related to FocusNode. Thanks and Sorry.
I have also fixed some compatibility issues with the latest versions of Flutter and Android SDK.

I would like to merge also this PR.  But I would like to exclude the Form Generator example, and just leave the Documentation changes, if you could remove the changes in the example and keep the documentation I will gladly merge this PR.

Thanks in advance

**Comment by joanpablo** [comment]
Hi @vasilich6107, there is a issue in this PR. It is complaining bout the ReactiveTouchSpin

**Comment by vasilich6107** [comment]
Hi @joanpablo
Fixed the issues

**Pull request merged**
