### PR TITLE
textfield controller

### PR DESCRIPTION
**Pull request by vasilich6107**

### CODE REVIEW

**Comment by joanpablo** [comment]
Hi @vasilich6107,

I'm planning to just expose the **controller** as a normal argument to the **ReactiveTextField**, and probably I will cancel this PR. At the very first beginning I thought this will solve any issue related to text selection, but I think now that this PR implementation will not solve all the use cases of text selection.

This implementation will help to initialize a Text Field with a selected value, but will not solve the use case when a developer wants to select all text of the text field when the *tap* on the text field. For example each time the user *click* or *tap* on the text field I want to select all the text in the text field.

That's why I will just expose the controller (I'm implementing it right now), and let the developer decide when to use it for text selection.

Thanks again.

After this implementation, I will release a version and then I will upgrade to the latest 2.8 Flutter version, with all the missing properties of widgets.

I saw the FocusNode exposure. I will include them after the previous changes.

**Comment by joanpablo** [comment]
Thanks once again

**Comment by vasilich6107** [comment]
@joanpablo this does not seem to be true
Here is an example of how it works without any issues
https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_text_field/example/lib/main.dart#L27

**Comment by joanpablo** [comment]
Hi @vasilich6107,

You are right, that will solve the use case of select text when the user taps on input.  Although your solution will work, I have decided to expose the controller so the developer consumers will be more familiar with exposing the controller as a normal TextField.

**Pull request closed without merging**
