### PR TITLE
Null Safety updates

### PR DESCRIPTION
**Pull request by gmcdowell**
All but 1 test passes.
You may need to take a look but hope this helps.

### CODE REVIEW

**Review by joanpablo — CHANGES_REQUESTED** [review]
Hi @gmcdowell,

Thanks for your contribution. I know you have worked a lot on this pull request. Sorry I haven't answer you before.
I have just released version 9.0.0. It hasn't many changes, but improve a bit more the typecasting and runtime error due to bad casting between widgets and controls. This release was almost ready several weeks ago, but I haven't released it because I wanted to be sure everything was well tested.

I would like you to rebase your pull request from master before I can review it. I want to review your PR but with all the new changes (there are not so many) to make sure everything is compatible.

Sorry for the inconvenience. And thanks once again. I really appreciate your collaboration and I think it is very useful for the community, and for me.

I sow you have updated to new Widgets too, That's great.  Good Job.

**Comment by radvansky-tomas** [comment]
@joanpablo here it is https://github.com/joanpablo/reactive_forms/pull/97

**Comment by gmcdowell** [comment]
hi @joanpablo 

glad to help and happy to continue to do so.

both @radvansky-tomas and I will continue to work with you as need.

let me know how you get on with the changes made post your initial feedback above eh.

**Comment by joanpablo** [comment]
Hi guys, @gmcdowell @radvansky-tomas 

I'm working on null-safety since yesterday. Because of the importance of this requirement and the detailed work that is needed to be done I've decided to do it completely by myself. I need to re-think, study and fully understand each line of code in the project and the changes they require to migrate to null-safety.

I will not reject the PR for now because it serves as a reference and I can take a look at your vision of the problem. After I have released the null-safety version you can update your forks and improve my work and fill any missing piece of code that I forget to change.

You will have the opportunity to contribute, officially (with your names in the repo) because you already are contributing and I really appreciate it and want to thank all of you once again.

Sorry for the inconvenience but I hope you can understand.

this release is going to be version 10.0.0 and will be a fully Flutter 2.0 compatible project. I just started yesterday, there is a lot of work to do yet. But I really believe that in the next couple of weeks the release will be ready.

Best Regards, and have a nice weekend ;)

Thanks for all the support.

**Comment by radvansky-tomas** [comment]
@joanpablo Thank you for your kind words, yes I've been talking about same think with @gmcdowell last week. You need to sit down, read what we've done and probably do your thing again. However we could not wait and started using our version, which we shared with you and community.

I would be definitely interested in becoming contributor and to code reviews in improvement of this great plugin.

**Pull request closed without merging**
