### PR TITLE
simplified focus node adding for TextField

### PR DESCRIPTION
**Pull request by vasilich6107**
Hi. I tried to migrate my former PR about type improvements #94 but it seems too much complicated to migrate and to use.
So I decided to extract focus node setting improvement from it.

### CODE REVIEW

**Comment by vasilich6107** [comment]
Hi @joanpablo 
Could you take a look?

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Sorry for the late answer, I have been busy recently. I will take a look and let you know. Right now I'm fixing some bugs.

**Comment by joanpablo** [comment]
Hi @vasilich6107,

I have released 10.4.1. In this version, I have simplified a bit setting the focus node to the reactive text field. What I'm not sure about you approach is that if you follow that path of putting the focusNode in the ReactiveTextField instead that in the State, then you should handle the **didUpdateWidget** method so you can check if the *focusNode* has been changed to a new one. The implementation I tried was more or less the same of the *didUpdateWidget* to detect if the focusNode has been changed but without using the overridden method *didUpdateWidget* at all.

**Comment by vasilich6107** [comment]
hi @joanpablo 
Isn't `didUpdateWidget` a better approach?
It utilize the default flutter approach + requires less code to work

**Pull request closed without merging**
