### PR TITLE
Allow developers to add custom controls

### LINKED ISSUE #162: AbstractControl not extensible
I need/want to implement a custom extension of `AbstractControl` but a couple of the private functions can not be overridden outside of the `models.dart` file which practically makes this impossible.

I think it would be good to separate all the classes form the `models.dart` file into separate files which will automatically lead to a class hierarchy that is extensible by developers.

I understand that a couple of these functions are not mean to be used from the outside but those that are overridden in `FormGroup` and `FormArray` need to be public.

### PR DESCRIPTION
**Pull request by kuhnroyal**
Hi @joanpablo,

this is a small PR that makes a couple methods `@protected` to allow developers to extend and create own types of controls.
Closes #162.

### CODE REVIEW

**Comment by joanpablo** [comment]
Hi @kuhnroyal,

Thanks a lot for your contributions, I have been very busy recently. Could you check why the "Codacy Static Code Analysis" is failing?

**Comment by kuhnroyal** [comment]
@joanpablo No worries, from what I can tell, `develop` is not analyzed. I can point the PR to `master`, that would probably succeed but not sure if that is correct.

**Comment by kuhnroyal** [comment]
@joanpablo I rebased this on master since the build doesn't work with develop.

**Comment by kuhnroyal** [comment]
@joanpablo I know you are busy, but could you look at this and see if you require any changes?

**Review by joanpablo — APPROVED** [review]
Thanks @kuhnroyal,

I see that you have make public some protected methods to allows other developers to create new CustomControls. Good idea. Thanks once again for supporting this package, I'm very happy with your help.

**Comment by kuhnroyal** [comment]
Would be great if this could be released :)

**Pull request merged**
