### PR TITLE
Null-Safety with 9.0.0 changes

### PR DESCRIPTION
**Pull request by radvansky-tomas**
Hi I work with Greg and did requested changes from 9.0.0 branch.
I also resolved that one failing tests we had before. Please review it and try to merge it at least to develop branch.

### CODE REVIEW

**Comment by joanpablo** [comment]
Hi @radvansky-tomas,

Thanks for both of you, and for your work. I will review it. I will let you know soon. I guess then that I should merge this request instead of the one from @gmcdowell ??

**Comment by radvansky-tomas** [comment]
yes correct, thank you for your time

**Comment by DevNico** [comment]
Flutter 2 is out and with it stable null safety a null safe version would be highly appreciated!

**Comment by joanpablo** [comment]
I guys, Hi @radvansky-tomas @gmcdowell  @DevNico,

I agree with you, null-safety is a Must now that Flutter 2 is announced. I have been working in stabilizations in type systems because something was broken in the last couple of releases, so that has been my focus. I feel responsible for bringing a stable plugin to the community. I'm waiting for a response to some issues related to the type system, after all those issues are solved my next focus is going to be null-safety and study and merge this PR.

**Comment by DevNico** [comment]
Could you mention the issues that are blocking for you so we can follow them too?

Also thank you for this great package!

**Comment by joanpablo** [comment]
Type related issues:
* [Type problems](https://github.com/joanpablo/reactive_forms/issues/102)
* [Error: type 'FormControl<dynamic>' is not a subtype of type 'int'](https://github.com/joanpablo/reactive_forms/issues/104)
* [value accessor error - type is not a subtype of type 'String' of 'viewValue'](https://github.com/joanpablo/reactive_forms/issues/106)

Pull Requests related to Type System:
* [type improvements](https://github.com/joanpablo/reactive_forms/pull/94)

**Comment by gmcdowell** [comment]
@joanpablo thanks for the update and insight into your priorities.
We are going to continue to work on refining our branch (we will consolidate things too) and will keep an eye on your progress.

Do reach out if there is anything we can assist with.

**Comment by joanpablo** [comment]
Thanks @gmcdowell for your kind words, and thanks for the patient of all of you. I have released a couple of versions that solved some issues and I finally have added **intl 0.17.0**, so the project is not yet null safety but at least it is using the last version of intl.

**Comment by kuhnroyal** [comment]
Really looking forward to this but I think a couple of `dynamic` things need to be removed before this is possible and valuable. See https://github.com/joanpablo/reactive_forms/issues/102#issuecomment-791387387

**Comment by DevNico** [comment]
Any updates on when a null safe version will be available? 😄

**Comment by joanpablo** [comment]
Hi guys, 

@DevNico I'm working on it. I will need one more week. It's almost done, but because I'm doing two refactorings (null-safety and strict type system) I will need more time.

**Comment by DevNico** [comment]
Alright thanks for the update. Please don't feel rushed, take your time! I just wanted to know how far along you are. 

Thank you for this great package!

**Comment by joanpablo** [comment]
Tomorrow I will push my branch so everybody can check my progress. All the library is already migrated to null safety but there are still some tests that are not running because of types of casting issues, I need to solve these casting issues in some way.

**Comment by cedvdb** [comment]
@joanpablo Thanks for the awesome work. I'm interested in using your branch it even if it's not production ready so I can start the null safety migration. So if it's possible to push it, it would be great

**Comment by joanpablo** [comment]
Hi guys @gmcdowell, @radvansky-tomas, @DevNico, @cedvdb

I have updated the **develop** branch with a fully functional version of **Recative Forms** using the latest version of Flutter with null-safety and a better type system. All tests are running OK. You can check it. I'm still working to improve minor things but I'm very close to release the new version.

@vasilich6107 you can update the reactive widgets library with the latest changes.

**Comment by vasilich6107** [comment]
Thanks for the update!

**Comment by vasilich6107** [comment]
@joanpablo I tried to use the dev branch for migration
One thing that I'd like to ask is to give more meaningful name for `ReactiveFormField<T, K>`

Previously there was only `T` and this was easy to understand - `T` is a type of value.
In case of multiple generic values there `T` and `K` are not very verbose

**Comment by joanpablo** [comment]
> @joanpablo I tried to use the dev branch for migration
> One thing that I'd like to ask is to give more meaningful name for `ReactiveFormField<T, K>`
> 
> Previously there was only `T` and this was easy to understand - `T` is a type of value.
> In case of multiple generic values - single letters `T` and `K` are not very verbose

I'm agree with you, I was planning to explain in the class Doc, but what do you suggest?

**Comment by joanpablo** [comment]
I have release v10.0.0 with null safety.

You can now test it. Now we are in a better position to continuously improve the package :)

Thanks to all of you.

**Comment by vasilich6107** [comment]
@joanpablo I can suggest
`TFormControl` which describes the type incoming from `FormControl` and `TField` which describes the type expected buy field

Here is how `control_value_accessor` will look like - https://tppr.me/kWbVX

**Comment by joanpablo** [comment]
> @joanpablo I can suggest
> `TFormControl`(instead of `T`) which describes the type incoming from `FormControl` and `TField`(instead of `K`) which describes the type expected by field
> 
> Here is how `control_value_accessor` will look like - https://tppr.me/kWbVX

I have already released before your suggestion :sweat_smile:

**Comment by vasilich6107** [comment]
If my suggestion is ok - I can make PR with update ;-)

**Comment by cedvdb** [comment]
do not prefix it both by T, it's not meaningful either. Just add Type. That's my suggestion. Honestly for generic names you don't really care to be a bit too verbose since it's not part of what's imediatly seen in the public API

**Comment by joanpablo** [comment]
Hi @cedvdb @vasilich6107,

I already put **ReactiveFormField<ModelDataType, ViewDataType>** is not a traditional name but I think it is quite understandable. I will keep that names for now. Thanks for the suggestions :)

**Comment by cedvdb** [comment]
@joanpablo Those names are fine imho

**Pull request closed without merging**
