### PR TITLE
more-reactive-widgets

### PR DESCRIPTION
**Pull request by vasilich6107**

### CODE REVIEW

**Comment by vasilich6107** [comment]
Hi @joanpablo 
Could you check my PR?

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Sorry I have been very busy recently. I will take a look and let you know soon. Thanks a lot for your support. You have been covering my back while I'm busy with other projects :)

**Review by joanpablo — APPROVED** [review]
Great job, as always

**Comment by vasilich6107** [comment]
Thanks for your support)

**Pull request merged**
