### PR TITLE
docs: update readme with testing examples

### PR DESCRIPTION
**Pull request by pumano**
Added example about how to test whole form to readme

## To Do

- [ ] Check the original issue to confirm it is fully satisfied
- [ ] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behaviour
- [ ] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Comment by joanpablo** [comment]
Thanks @pumano

**Comment by pumano** [comment]
I updated recently with Validators.email

**Comment by pumano** [comment]
@joanpablo thank you for amazing library. I got perfect angular experience here :)

**Comment by joanpablo** [comment]
> @joanpablo thank you for amazing library. I got perfect angular experience here :)

Thanks @pumano for your kind words.

**Pull request merged**
