### PR TITLE
switch list tile fix

### PR DESCRIPTION
**Pull request by vasilich6107**

### CODE REVIEW

**Comment by vasilich6107** [comment]
I will fix tests

**Comment by joanpablo** [comment]
Excellent @vasilich6107, as always good job.

Before merging the PR could you add a Test to the ReactiveSwitchListTile? 

The test must validate that: If the value of the control is NULL then that value of the ReactiveSwitchListTile is false.

Thanks once again

**Comment by vasilich6107** [comment]
Of course
I'm deep in writing generator
I will fix the tests this week

**Comment by joanpablo** [comment]
There is a similar test in the tests of the ReactiveSwitch widget

**Comment by vasilich6107** [comment]
@joanpablo 95.09% (+0.63%) compared to 6c46d0b ;-)

**Review by joanpablo — APPROVED** [review]
Excellent @vasilich6107. Thanks a lot

**Pull request merged**
