### PR TITLE
Fix dropdown field wrapper

### PR DESCRIPTION
**Pull request by mohn93**
Removed the input decoration implementation in the wrapper and just passed decoration to the drop-down widget, so it handles all the decoration and spacing

### CODE REVIEW

**Comment by mohn93** [comment]
This will allow us to let the inkwell ripple effect expand to the edges of the fields, as it supposed to

**Comment by mohn93** [comment]
@joanpablo, Anything I can do so you can merge?

**Comment by joanpablo** [comment]
Hi @mohn93 sorry the delay but the PR is not building correctly there are some issues. Could you fix those issues first? Thanks

**Comment by mohn93** [comment]
@joanpablo, Could you check now, please?

**Comment by joanpablo** [comment]
It looks like we had a regression on testing coverage. Doesn't it?

**Comment by mohn93** [comment]
@joanpablo, Sorry, Can you check now?

**Comment by mohn93** [comment]
@joanpablo , Sorry, Can you check now?

**Comment by joanpablo** [comment]
Hi @mohn93 seams like 1 file is failing because a formatting error.

**Comment by mohn93** [comment]
@joanpablo , May I ask what the error is exactly?

**Comment by joanpablo** [comment]
The file `test/src/widgets/reactive_dropdown_field_test.dart` does not comply with formating rules for a flutter dart file.

**Comment by mohn93** [comment]
@joanpablo Pushed

**Comment by mohn93** [comment]
@joanpablo  Please check

**Pull request merged**
