### PR TITLE
type improvements

### PR DESCRIPTION
**Pull request by vasilich6107**
Hi. It's me and types again)

### CODE REVIEW

**Comment by vasilich6107** [comment]
The most useful benefit of the PR could be found in
https://github.com/joanpablo/reactive_forms/pull/94/files#diff-e9a5a50eeaa49ffc058e5c80151cfa979b22db7017a938328b90ef137dc52fb8

**Comment by vasilich6107** [comment]
I added two more types for simplification of development
`ReactiveFormFieldValue` and `ReactiveFormFieldStateValue`

I could not make it easier due to the `recursive type` error during compilation.

**Comment by vasilich6107** [comment]
I was implementing a wrapper for (signature)[https://pub.dev/packages/signature] package

The (SignatureController)[https://github.com/4Q-s-r-o/signature/blob/master/lib/signature.dart#L176] requires more than one parameter. So I decided that type system improvement will be a good tradeoff to making a bunch of functions.

```
_setPenColor { ... }

_setPenStrokeWidth  { ... }

_setExportBackgroundColor  { ... }
```

**Comment by vasilich6107** [comment]
It this approach works for you - I'll update the docs.

**Comment by vasilich6107** [comment]
Hi @joanpablo 
Could you check my PR)

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Thanks again for your work. I know you have worked hard for this PR, and I really appreciate it. You are one of the contributors with more contributions to this project and I really appreciate it. You have done great work as always. I will give you soon my considerations about the PR.

Have a nice weekend

**Comment by vasilich6107** [comment]
Hi @joanpablo 
Thanks for your kind words
I fixed conflicts and ready for discussion :-)

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Sorry for making you wait so long for my answer. Since the relevance of the null-safety, I have decided to start working on it. I started the migration yesterday. With the migration to null-safety, many strong type issues will show out. So I think that after the migration we will be in a better position to re-evaluate the strong type system. 

That's why I have decided to close this PR temporarily since my main focus will be the null-safety migration. You have always contributed with great ideas, I hope you continue the same way helping me in the future. Sorry for the inconvenience.

Best regards and have a nice weekend.

**Comment by vasilich6107** [comment]
Sure. Null safety has higher priority.
Let’s continue with types after migrating both libs to null safety. 
I’ll look into converting widgets into monorepo in the meantime

**Comment by vasilich6107** [comment]
Hi @joanpablo 
Do you have any issues with null safety migration?
Maybe I could help with something?

**Pull request closed without merging**
