### PR TITLE
package split

### PR DESCRIPTION
**Pull request by vasilich6107**

### CODE REVIEW

**Comment by vasilich6107** [comment]
All test after splitting is ok
image

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Some checks did not pass (The Analyze task). Could you take a look, please?

And also could you give me a brief description of this PR? It touches a lot of files in the project.

Best regards

**Comment by vasilich6107** [comment]
This PR is required to implement https://github.com/joanpablo/reactive_forms/issues/176

**Comment by vasilich6107** [comment]
In the meantime @joanpablo could you read through the #176 to get along with current progres.
May be you'll have some comments

**Comment by kuhnroyal** [comment]
I don't think this is needed. See https://github.com/joanpablo/reactive_forms/issues/176#issuecomment-885022405

**Comment by vasilich6107** [comment]
@kuhnroyal unfortunately this is needed(

Here is why.

For writing correct `FormControl` annotation I need this
https://github.com/artflutter/reactive_forms_generator/blob/master/packages/reactive_forms_annotations/lib/src/form_array_annotation.dart

I need to import `ValidatorFunction` and `AsyncValidatorFunction` from package.
I could write them manually but they both refer to `AbstractControl`.

This is why I need runtime dependancy.

The code generators are not allowed to include packages which depend on `flutter`.

In test I'm getting 
image

While trying to generate
image

**Comment by kuhnroyal** [comment]
Created you a sample PR that shows how to do this without the split: https://github.com/artflutter/reactive_forms_generator/pull/1

**Comment by vasilich6107** [comment]
@joanpablo i think @kuhnroyal knows some magic)
His example definitely works)

I will get back to development next week

**Pull request closed without merging**
