### PR TITLE
reactive dropdown props update

### PR DESCRIPTION
**Pull request by vasilich6107**

### CODE REVIEW

**Comment by joanpablo** [comment]
The issue about the missing properties is related to the version of Flutter. In recent versions of Flutter, the dropdown has included new properties that are not included in Reactive Forms because of the version of Flutter, we cannot just add the new properties. We need to upgrade the minimum version of Flutter that Reactive Forms depends on.

**Comment by joanpablo** [comment]
First, we need to identify in what version of Flutter these new properties were included. And release a version of Reactive Forms that set this version as a minimum Flutter SDK version.

That is why this Pipeline is failing because is running the test with a version of Flutter that does not include all these properties.

**Comment by joanpablo** [comment]
BTW @vasilich6107,

Great Job once again. Thanks to your dedication and for supporting me, even in all these past months that I have been so busy. Thanks again for all your contribution.

:smiley: :clap: :tada: :rocket:

**Comment by vasilich6107** [comment]
No problem @joanpablo

**Comment by joanpablo** [comment]
This is included in v11.0.0

**Pull request closed without merging**
