### PR TITLE
Improve required validator #377

### LINKED ISSUE #377: RequiredValidator to flag empty lists and maps in addition to nulls and empty strings
Currently the `RequiredValidator` only handles cases of null values and empty strings. And the doc reads: "Validator that requires the control have a non-empty value.". Should we handle empty lists and maps as well? Would be happy to submit a PR if this makes sense.

### PR DESCRIPTION
**Pull request by vasilich6107**
## Connection with issue(s)

Close #377

### CODE REVIEW

**Comment by joanpablo** [comment]
Hi @vasilich6107 

Thanks for been so diligent and taking care of the comments. In this particular case I'm not sure we want to merge both concepts in the same Validator. You can check my answer in the issue https://github.com/joanpablo/reactive_forms/issues/377

**Comment by joanpablo** [comment]
Maybe creating another validator that serves as an alias to the Validators.minLength(1), something like Validators.isNotEmpty could work out

**Comment by laogao** [comment]
> Maybe creating another validator that serves as an alias to the Validators.minLength(1), something like Validators.isNotEmpty could work out

There is one caveat for `minLength(1)`, which concerns numbers. I much prefer a `NonEmptyValidator` to an alias to `Validators.minLength(1)`, and "re-use" the `ValidationMessages.required` key. (See my comment in #377 .)

**Comment by joanpablo** [comment]
I will close this PR since the discussion is still open.

**Pull request closed without merging**
