### PR TITLE
switch focus node

### PR DESCRIPTION
**Pull request by vasilich6107**

### CODE REVIEW

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Is this PR based on the latest 11.0.0 version? I want to make sure that everything that is in v11 is also here.

**Comment by vasilich6107** [comment]
@joanpablo yes you are safe to merge it

**Comment by joanpablo** [comment]
Good, just review the other PR, because some of them have merge conflicts.k

**Comment by vasilich6107** [comment]
@joanpablo i fixed all of them already

**Comment by vasilich6107** [comment]
@joanpablo as far as we done with urgent bugs - could we merge PRs

**Comment by joanpablo** [comment]
> them already

Ok, @vasilich6107 sorry for the delay. this week I will study the PR, and make a decision. I know that you have changed widgets to support the focus handling, and there is another about the documentation, but also make some changes to the Example.

I haven't merged the one with documentation because I need to be sure what you changed in the example. I prefer to have 1 PR with documentation changes and another with *example* changes. Because the example as far as I saw includes the reactive forms code-generator and I'm not sure about that. I prefer to have a separate example and not mix both examples.

Best

**Pull request merged**
