### PR TITLE
ci: Add deployment job to workflow

### PR DESCRIPTION
**Pull request by deandreamatias**
Close: #198 

- Upgrade github actions versions
- Remove unnecessary comments
- Add check publish warnings job to workflow
- Add deployment job to workflow

⚠️ @joanpablo to this pipeline works, need two thinks:

- Get the enviroment `PUB_DEV_PUBLISH_ACCESS_TOKEN` and `PUB_DEV_PUBLISH_REFRESH_TOKEN`
  - Take a look on [this article](https://dennis.alund.me/blog/publishing-dart-packages-with-github-actions/) or [this comment](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/pull/1051#discussion_r899378034)
- To add the token to repository, go to Settings > Actions > Press on New repository secret
Is **not** a enviroment secret, is a **repository secret**

This an image that my configuration for [flutter_form_builder](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder)
Your token will be configure below repository secrets, because is a single repository and no an organization

image

### CODE REVIEW

**Comment by mdeandrea-mrmilu** [comment]
Hi @vasilich6107 and @kuhnroyal please can take a look in this PR and [this comment](https://github.com/joanpablo/reactive_forms/issues/198#issuecomment-1272012702)? Thanks

**Comment by joanpablo** [comment]
Thanks, @mdeandrea-mrmilu.

So as far as I understand this deployment will only be triggered if a Tag is created, and not when simply pushing changes to master or develop. Could you confirm that, please?

**Comment by deandreamatias** [comment]
Yes, I confirm this, only with tag created.
Today, after sent this comment, I watch [this video](https://youtu.be/7LFftXcw1jA?t=767) about automatic deploy of packages. Maybe is a way more secure and improved that this code change

**Comment by joanpablo** [comment]
Oh, thanks for sharing the video @deandreamatias I will see it, and let you know my comments about it.

**Comment by deandreamatias** [comment]
@joanpablo branch updated!

**Pull request merged**
