### PR TITLE
checkbox focus node

### PR DESCRIPTION
**Pull request by vasilich6107**

### CODE REVIEW

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Is this PR based on the latest 11.0.0 version? I want to make sure that everything that is in v11 is also here.

**Comment by vasilich6107** [comment]
@joanpablo yes you are safe to merge it

**Comment by vasilich6107** [comment]
Hi @joanpablo 
Could you merge this PRs

**Comment by vasilich6107** [comment]
@joanpablo could you review this PR?
Two month has gone...

**Pull request merged**
